name: Verify changes

on: pull_request

jobs:
  verify:
    name: Verify changes
    strategy:
      matrix:
        # latest node & minimum node according to pkg.json engines
        node-version: [21.0, 23.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Linting & Formatting
        run: npm run lint

      - name: Tests
        run: npm run test
